# Generated by Django 4.2.29 on 2026-03-25 16:09

import browse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0007_alter_datafile_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="tarball",
            field=models.FileField(
                blank=True,
                editable=False,
                help_text="A tarball of the release, including full json file,         format specifications, and data files, ready to be downloaded",
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="name",
            field=models.CharField(
                help_text="Descriptive name for this entity",
                max_length=512,
                validators=[browse.models.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="formatspecification",
            name="doc_file_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the file containing the specification document (optional)",
                max_length=1024,
                null=True,
                verbose_name="name of the file containing the specification document",
            ),
        ),
        migrations.AlterField(
            model_name="formatspecification",
            name="document_ref",
            field=models.CharField(
                help_text="ID of the technical document",
                max_length=256,
                unique=True,
                verbose_name="ID of the specification document",
            ),
        ),
        migrations.AlterField(
            model_name="formatspecification",
            name="title",
            field=models.CharField(
                help_text="Title of the document containing the specification for a file format",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="name",
            field=models.CharField(
                help_text="Descriptive name for this quantity",
                max_length=512,
                validators=[browse.models.validate_name],
            ),
        ),
    ]
